# Generated by Django 5.1.3 on 2024-12-06 20:22

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('MAÑANA', '8:00 - 13:00'), ('TARDE', '13:00 - 18:00'), ('COMPLETO', '9:00 - 18:00')], max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('ATENCION_CLIENTE', 'Atención al Cliente'), ('CAJA', 'Caja'), ('PRESTAMOS', 'Préstamos'), ('INVERSIONES', 'Inversiones'), ('ADMINISTRACION', 'Administración'), ('GERENCIA', 'Gerencia')], max_length=50)),
                ('nivel', models.CharField(choices=[('JUNIOR', 'Junior'), ('SEMI_SENIOR', 'Semi Senior'), ('SENIOR', 'Senior'), ('SUPERVISOR', 'Supervisor'), ('GERENTE', 'Gerente')], max_length=20)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField()),
            ],
            options={
                'ordering': ['area', 'nivel'],
                'unique_together': {('nombre', 'nivel')},
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='DNI debe contener 8 dígitos', regex='^\\d{8}$')])),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^\\+?1?\\d{9,15}$')])),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_contratacion', models.DateField(default=datetime.date.today)),
                ('direccion', models.CharField(max_length=200)),
                ('numero_legajo', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('vacaciones_disponibles', models.IntegerField(default=15)),
                ('evaluacion_desempeño', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.cargo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='clientes.sucursal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.turno')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'ordering': ['-fecha_contratacion'],
                'permissions': [('can_evaluate', 'Puede evaluar empleados'), ('can_assign_vacation', 'Puede asignar vacaciones')],
            },
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('ENFERMEDAD', 'Enfermedad'), ('PERSONAL', 'Personal'), ('OTROS', 'Otros')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('justificacion', models.TextField(blank=True)),
                ('aprobada', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='empleados.empleado')),
            ],
            options={
                'verbose_name_plural': 'Ausencias',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
