# Generated by Django 5.1.3 on 2024-12-06 22:27

import cuentas.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('AHORRO', 'Cuenta de Ahorro'), ('CORRIENTE', 'Cuenta Corriente'), ('INVERSION', 'Cuenta de Inversión'), ('DIGITAL', 'Cuenta Digital')], max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('mantenimiento_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('limite_transferencia_diaria', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('limite_retiro_diario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('saldo_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Tipo de Cuenta',
                'verbose_name_plural': 'Tipos de Cuenta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número de cuenta debe tener 10 dígitos', regex='^\\d{10}$')])),
                ('cbu', models.CharField(max_length=22, unique=True, validators=[django.core.validators.RegexValidator(message='El CBU debe tener 22 dígitos', regex='^\\d{22}$')])),
                ('alias', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='El alias solo puede contener letras, números y puntos', regex='^[a-zA-Z0-9.]+$')])),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos Argentinos'), ('USD', 'Dólares Estadounidenses'), ('EUR', 'Euros')], default='ARS', max_length=3)),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('BLOQUEADA', 'Bloqueada'), ('EN_REVISION', 'En Revisión')], default='ACTIVA', max_length=15)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to=settings.AUTH_USER_MODEL)),
                ('tipo_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentas.tipocuenta')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['-fecha_apertura'],
                'unique_together': {('titular', 'tipo_cuenta', 'moneda')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('RETIRO', 'Retiro'), ('TRANSFERENCIA_ENVIADA', 'Transferencia Enviada'), ('TRANSFERENCIA_RECIBIDA', 'Transferencia Recibida'), ('PAGO_SERVICIO', 'Pago de Servicio'), ('INTERES', 'Interés'), ('COMISION', 'Comisión')], max_length=25)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(max_length=200)),
                ('referencia', models.CharField(blank=True, default=cuentas.models.generar_referencia, max_length=50, null=True, unique=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='cuentas.cuenta')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
