# Generated by Django 5.1.3 on 2024-12-06 22:27

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='marcas/')),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Marca de Tarjeta',
                'verbose_name_plural': 'Marcas de Tarjetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('beneficios', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tarjeta',
                'verbose_name_plural': 'Tipos de Tarjetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='El número debe contener 16 dígitos', regex='^\\d{16}$')])),
                ('fecha_expiracion', models.DateField()),
                ('fecha_otorgamiento', models.DateField(default=datetime.date.today)),
                ('cvv', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='El CVV debe contener 3 dígitos', regex='^\\d{3}$')])),
                ('tarjeta_principal', models.BooleanField(default=False)),
                ('background', models.CharField(choices=[('1', 'Estilo 1'), ('2', 'Estilo 2'), ('3', 'Estilo 3')], default='1', max_length=1)),
                ('activa', models.BooleanField(default=True)),
                ('limite_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas', to='clientes.cliente')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarjetas.marcatarjeta')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarjetas.tipotarjeta')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'ordering': ['-fecha_otorgamiento'],
                'unique_together': {('numero', 'marca')},
            },
        ),
    ]
